apiVersion: v1
kind: Service
metadata:
  name: despachos
spec:
  ports:
    - port: 8081
      targetPort: 8081
  selector:
    app: despachos
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: despachos
spec:
  selector:
    matchLabels:
      app: despachos
  template:
    metadata:
      labels:
        app: despachos
    spec:
      containers:
      - name: despachos
        image: <IMAGE_DESPACHOS>
        ports:
        - containerPort: 8081
        env:
        - name: DB_ENDPOINT
          value: mysql
        - name: DB_PORT
          value: "3306"
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: name
        - name: DB_USERNAME
          value: root
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: password
        - name: SERVER_PORT
          value: "8081"
